I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Soldier/Day 1/2_Drinks/2b_nurse.rpy", line 3, in script call
    call nurse_generic
  File "game/scripts/Soldier/Generic Conversations/nurse.rpy", line 6, in script call
    call nurse_generic_1
  File "game/scripts/Soldier/Generic Conversations/nurse.rpy", line 15, in script
    show nurse nervous
Exception: Image 'nurse' does not accept attributes 'nervous'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Soldier/Day 1/2_Drinks/2b_nurse.rpy", line 3, in script call
    call nurse_generic
  File "game/scripts/Soldier/Generic Conversations/nurse.rpy", line 6, in script call
    call nurse_generic_1
  File "game/scripts/Soldier/Generic Conversations/nurse.rpy", line 15, in script
    show nurse nervous
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'nurse' does not accept attributes 'nervous'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Murder 1.0
Thu Jun 16 12:08:12 2022
